apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: antx
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        imagePullPolicy: Always
        image: localhost:5000/backend:latest
        command:
        - /bin/bash
        - -c
        args:
        - fastapi dev api.py
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: 500m
            memory: 528M
          limits:
            cpu: 1
            memory: 1Gi
        env:
          - name: READ_BUCKET
            value: "###ZARF_VAR_S3_READ_BUCKET_NAME###"
          - name: WRITE_BUCKET
            value: "###ZARF_VAR_S3_WRITE_BUCKET_NAME###"
          - name: VALKEY_HOST
            value: "###ZARF_VAR_VALKEY_HOST###"
          - name: VALKEY_PASSWORD
            value: "###ZARF_VAR_VALKEY_PASSWORD###"
          - name: VALKEY_PORT
            value: "###ZARF_VAR_VALKEY_PORT###"
          - name: S3_REGION
            value: "###ZARF_VAR_S3_REGION###"
          - name: S3_ENDPOINT
            value: "###ZARF_VAR_S3_ENDPOINT###"
          - name: LEAPFROG_API_KEY
            value: "###ZARF_VAR_LEAPFROG_API_KEY###"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: antx
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
